#!/usr/bin/env bash
# the Commands to install Nginx on the Web-Sever-01

# this updates Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# this Configures Uncomplicated Firewall (UFW) to allow incoming traffic for Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# this Creats an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# this tests Nginx configurations for Syntax errors
sudo nginx -t

# this restarts Nginx
sudo service nginx start
