#!/usr/bin/env bash
#  Script that configures new Ubuntu machine to Perform 301-redirection

# Updates Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creates index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performs 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/zakry27 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarts Nginx service
sudo service nginx restart
