#!/usr/bin/env bash
# Customize 404-error_page

# Update Packages before performing instal
sudo apt-get update
sudo apt-get install -y nginx

# Create index.htmle
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performe "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/zakry27 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Create 404 Custom error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
