#!/usr/bin/env bash
# Creates script to install and configure HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests using roundrobin algorithm
# Makes sure that HAProxy can be managed via init script

# Install and configures HAproxy on lb-01 server.
sudo apt-get update
sudo apt-get install haproxy

# edit config file
server_config=\
"
frontend  zakry27_frontend
        bind *:80
        mode http
        default_backend zakry27_backend
backend zakry27_backend
        balance roundrobin
        server 455458-web-01 100.25.177.25:80 check
        server 455458-web-02 34.229.186.10:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
