#!/usr/bin/env bash
# this is same as task 0 but -f is added to ln to force the removall of file if exists

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
